require("options")
require("keymaps")
require("language-servers")

require("plugins.oil")
require("plugins.cord")
require("plugins.telescope")
require("plugins.catppuccin")
require("plugins.gitsigns")
require("plugins.conform")
require("plugins.autopairs")
require("plugins.noice")
require("plugins.trouble")
require("plugins.lualine")
