require("options")
require("keymaps")

require("plugins.oil")
require("plugins.cord")
require("plugins.telescope")
require("plugins.catppuccin")
require("plugins.gitsigns")
require("plugins.conform")
require("plugins.autopairs")
